version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
